# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180317_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank='True', default='default.jpg', upload_to='upload_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 19, 30, 16, 961019, tzinfo=utc)),
        ),
    ]
