# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 00:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180318_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 0, 50, 46, 672521, tzinfo=utc)),
        ),
    ]
